name: Film scrape

on:
  push:
    branches:
      - main
  schedule:
    # Run twice a day at 8:30 and 13:30 UTC (see https://crontab.guru)
    - cron:  '30 8,13 * * *'

jobs:
  scrape_films_and_seed_mongodb:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node.js 16.3
        uses: actions/setup-node@v3
        with:
          node-version: '16.3'
      - name: Clean install
        run: npm ci
      - name: Scrape now showing films
        run: npm run scrape
      - name: Exec BABASHKA script
        uses: tzafrirben/babashka-docker-action@v1.1
        id: bb_script
        with:
          bb_src: 'bb-test-script.clj'
      - name: Get BABASHKA script output
        run: echo "${{ steps.bb_script.outputs.bb_out }}"
      - name: Seed DB
        run: npm run seed
        env:
          ATLAS_URI: ${{ secrets.ATLAS_URI }}
      
      
      
