name: Film scrape

on:
  push:
    branches:
      - main
      - develop
  schedule:
    # Run twice a day at 1:30 (12:30 PM AEDT) and 21:30 UTC (8:30 AM AEDT) (see https://crontab.guru)
    - cron:  '30 1,21 * * *'

jobs:
  scrape_films_and_seed_mongodb:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node.js 16.3
        uses: actions/setup-node@v3
        with:
          node-version: '16.3'
      - name: Clean install
        run: npm ci
      - name: Scrape
        run: npm run scrape
        env:
          API_KEY: ${{ secrets.API_KEY }}
          RITZ_URL: ${{ secrets.RITZ_URL }}
          TMDB_URL: ${{ secrets.TMDB_URL }}
      - name: Seed DB
        if: steps.validateJSON.outcome == 'success'
        run: npm run seed
        env:
          ATLAS_URI: ${{ secrets.ATLAS_URI }}
          MONGODB_DATABASE: ${{ secrets.MONGODB_DATABASE }}
          MONGODB_COLLECTION: ${{ secrets.MONGODB_COLLECTION }}