name: Trigger script run on a CRON schedule

on:
  schedule:
    # UTC (see https://crontab.guru)
    - cron:  '30 8,13 * * *'

jobs:
  run_puppeteer_script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.3
        uses: actions/setup-node@v3
        with:
          node-version: '16.3'
      - run: npm ci
      - run: npm run scrape
      
