name: Film scrape

on:
  push:
    branches:
      - main
  schedule:
    # Run twice a day at 8:30 and 13:30 UTC (see https://crontab.guru)
    - cron:  '30 8,13 * * *'

jobs:
  scrape_films_and_seed_mongodb:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.3
        uses: actions/setup-node@v3
        with:
          node-version: '16.3'
      - run: npm ci
      - run: npm run scrape
      - run: npm run seed
        env:
          ATLAS_URI: ${{ secrets.ATLAS_URI }}
      
      
