name: Film scrape

on:
  push:
    branches:
      - main
      - develop
  schedule:
    # Run twice a day at 1:30 (12:30 PM AEDT) and 21:30 UTC (8:30 AM AEDT) (see https://crontab.guru)
    - cron:  '30 1,21 * * *'

jobs:
  scrape_films_and_seed_mongodb:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node.js 16.3
        uses: actions/setup-node@v3
        with:
          node-version: '16.3'
      - name: Clean install
        run: npm ci
      - name: Scrape
        run: npm run scrape
      - name: Validate JSON
        id: validateJSON
        run: |
          npm run test
      - name: Seed DB
        if: steps.validateJSON.outcome == 'success'
        run: npm run seed
        env:
          ATLAS_URI: ${{ secrets.ATLAS_URI }}
          MONGODB_DATABASE: ${{ secrets.MONGODB_DATABASE }}
          MONGODB_COLLECTION: ${{ secrets.MONGODB_COLLECTION }}
  automated-api-tests:
    needs: scrape_films_and_seed_mongodb
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}
      - name: Run API tests
        run: |
          postman collection run "23726650-6f816ae0-8c9f-48ae-98f4-e89545ee1063" -e "23726650-27364fcd-9e55-431b-93a1-18daf30b3548"
      
      
      
