name: Trigger script run on a CRON schedule

on:
  schedule:
    # Runs "at 12:30 daily" (see https://crontab.guru)
    - cron: '30 12 * * *'
jobs:
  run_puppeteer_script:
    runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.3'
    - name: Install dependencies
      run: npm ci
    - name: Run scraper
      run: npm run scrape
      
